global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.sendgrid.net:587'
  smtp_hello: 'localhost'
  smtp_from: 'mxfiliz@gmail.com'
  smtp_auth_username: 'apikey'
  smtp_auth_password: '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'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email-notifications'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'mxfiliz@gmail.com'
    send_resolved: true
