services:
  database:
    image: mongo:latest
    container_name: avans-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: db_admin
      MONGO_INITDB_ROOT_PASSWORD: secure_password
      MONGO_INITDB_DATABASE: avans_db
    volumes:
      - ./mongodb-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - devops-avans-network

  api:
    build:
      context: ./week1
      dockerfile: Dockerfile
    container_name: avans-api
    restart: always
    environment:
      - PORT=12345
      - MONGO_URL=mongodb://db_admin:secure_password@database:27017/avans_db?authSource=admin
    ports:
      - "3000:12345"
    volumes:
      - ./week1:/app
      - /app/node_modules
    networks:
      - devops-avans-network
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: avans-frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - devops-avans-network
    depends_on:
      - api

  db-exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: db-exporter
    command:
      - --collect-all
      - --mongodb.uri=mongodb://db_admin:secure_password@database:27017/admin
    environment:
      - MONGODB_URI=mongodb://db_admin:secure_password@database:27017/admin
    networks:
      - devops-avans-network
    depends_on:
      - database

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - devops-avans-network
    depends_on:
      - api
      - db-exporter
      - alertmanager

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - "9093:9093"
    networks:
      - devops-avans-network

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    container_name: grafana
    restart: always
    ports:
      - "4000:3000"
    networks:
      - devops-avans-network
    depends_on:
      - prometheus

networks:
  devops-avans-network:
    driver: bridge

volumes:
  mongodb-data:
