name: CI Full Stack

on:
  push:
    paths:
      - 'week1/**'
      - 'worker-service/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  statuses: write
  checks: write

jobs:
  api-test-and-coverage:
    name: API Tests and Coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./week1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm ci
      - name: Fix Windows Permissions
        run: chmod +x ./node_modules/.bin/eslint || true
      - name: Run ESLint
        run: npm run lint
      - name: Run Tests & Code Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: ./week1
          threshold: 70
          github-token: ${{ secrets.GITHUB_TOKEN }}

  worker-tests:
    name: Worker Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./worker-service
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm install
      - name: Run Unit Tests
        run: npm test
